import { NextPairResponse } from '../../../../types';

export const runwayPhotos = [
	{
		name: 'Amoeba Bacteria',
		queen_name: 'Bimini Bon Boulash',
		franchise: `Drag Race UK`,
		season: 2,
		image_url: 'bimini-bacteria',
	},
	{
		name: 'Tartan',
		queen_name: 'Violet Chachki',
		franchise: `RuPaul's Drag Race`,
		image_url: 'chachki-tartan',
	},
	{
		name: 'Freddy Krueger',
		queen_name: 'Crystal Methyd',
		franchise: `RuPaul's Drag Race`,
		season: 12,
		image_url: 'crystal-krueger',
	},
	{
		name: 'Black and White',
		queen_name: 'Detox',
		franchise: `All Stars`,
		season: 2,
		episode: 1,
		episodeName: 'All Star Talent Show Extravaganza',
		image_url: 'detox-black-white',
	},
	{
		name: 'Pirate Entrance',
		queen_name: 'Gigi Goode',
		franchise: `RuPaul's Drag Race`,
		season: 12,
		episode: 1,
		image_url: 'gigi-pirate',
	},
	{
		name: 'All Stars Promo',
		queen_name: 'Gottmik',
		franchise: `All Stars`,
		image_url: 'gottmik-promo',
	},
	{
		name: 'Scream Dress',
		queen_name: 'Gottmik',
		franchise: `RuPaul's Drag Race`,
		season: 13,
		image_url: 'gottmik-scream',
	},
	{
		name: 'Promo',
		queen_name: 'Jimbo',
		franchise: `All Stars`,
		image_url: 'jimbo-promo',
	},
	{
		name: 'Pearl',
		queen_name: 'Plastique Tiara',
		franchise: `RuPaul's Drag Race`,
		season: 11,
		image_url: 'plastique-pearl',
	},
	{
		name: 'All Stars Promo',
		queen_name: 'Plastique Tiara',
		franchise: `All Stars`,
		image_url: 'plastique-promo',
	},
	{
		name: 'Finale',
		queen_name: 'Priyanka',
		franchise: `Canada's Drag Race`,
		season: 1,
		image_url: 'priyanka-finale',
	},
	{
		name: 'Finale',
		queen_name: 'Sasha Colby',
		franchise: `RuPaul's Drag Race`,
		season: 15,
		image_url: 'sasha-colby-finale',
	},
	{
		name: `Love the Skin You're In`,
		queen_name: 'Shea Couleé',
		franchise: `All Stars`,
		season: 5,
		episode: 5,
		episodeName: 'Snatch Game of Love',
		image_url: 'shea-love-skin',
	},
	{
		name: 'Sleeping Bag Dress',
		queen_name: 'Utica Queen',
		franchise: `RuPaul's Drag Race`,
		season: 13,
		episode: 7,
		episodeName: 'Bossy Rossy: The RuBoot',
		image_url: 'utica-sleeping-bag',
	},
	{
		name: 'Entrance',
		queen_name: 'Starlet',
		franchise: `Drag Race UK`,
		season: 4,
		episode: 1,
		image_url: 'starlet-entrance',
	},
	{
		name: 'Season 8 Finale',
		queen_name: 'Violet Chachki',
		franchise: `RuPaul's Drag Race`,
		season: 8,
		episode: 12,
		episodeName: 'Grand Finale',
		image_url: 'violet-chachki-finale',
	},
	{
		name: 'Three Heads Finale',
		queen_name: 'Willow Pill',
		franchise: `RuPaul's Drag Race`,
		season: 14,
		image_url: 'willow-pill-heads',
	},
	{
		name: 'Mushroom',
		queen_name: 'Willow Pill',
		franchise: `RuPaul's Drag Race`,
		season: 14,
		image_url: 'willow-pill-mushroom',
	},
];

export const initialPair: NextPairResponse = {
	message: 'Initial pair',
	authenticated: false,
	user: null,
	nextPair: [
		{
			_id: '66c5001eb804fda11a916db6',
			name: 'Snatch Game',
			queen_name: 'Jinkx Monsoon',
			franchise: "RuPaul's Drag Race",
			season: 5,
			episode: 5,
			episode_name: 'Snatch Game',
			score: 1978,
			ratings_count: 47,
			image_url: 'https://example.com/images/jinkx_snatch_game.jpg',
		},
		{
			_id: '66c5001eb804fda11a916dba',
			name: 'Drag on a Dime',
			queen_name: 'Temp data',
			franchise: "RuPaul's Drag Race",
			season: 4,
			episode: 1,
			episode_name: 'RuPocalypse Now!',
			score: 1865,
			ratings_count: 47,
			image_url: 'https://example.com/images/sharon_drag_on_a_dime.jpg',
		},
	],
};
