const foods = [
  { name: "Apple", rank: 100 },
  { name: "Banana", rank: 100 },
  { name: "Orange", rank: 100 },
  { name: "Grape", rank: 100 },
  { name: "Strawberry", rank: 100 },
  { name: "Mango", rank: 100 },
  { name: "Pineapple", rank: 100 },
  { name: "Watermelon", rank: 100 },
  { name: "Blueberry", rank: 100 },
  { name: "Kiwi", rank: 100 },
  { name: "Broccoli", rank: 100 },
  { name: "Carrot", rank: 100 },
  { name: "Potato", rank: 100 },
  { name: "Tomato", rank: 100 },
  { name: "Onion", rank: 100 },
  { name: "Lettuce", rank: 100 },
  { name: "Spinach", rank: 100 },
  { name: "Cucumber", rank: 100 },
  { name: "Bell pepper", rank: 100 },
  { name: "Corn", rank: 100 },
  { name: "Rice", rank: 100 },
  { name: "Bread", rank: 100 },
  { name: "Pasta", rank: 100 },
  { name: "Oatmeal", rank: 100 },
  { name: "Quinoa", rank: 100 },
  { name: "Cornbread", rank: 100 },
  { name: "Couscous", rank: 100 },
  { name: "Barley", rank: 100 },
  { name: "Rye bread", rank: 100 },
  { name: "Wheat berries", rank: 100 },
  { name: "Chicken", rank: 100 },
  { name: "Beef", rank: 100 },
  { name: "Fish", rank: 100 },
  { name: "Eggs", rank: 100 },
  { name: "Tofu", rank: 100 },
  { name: "Beans", rank: 100 },
  { name: "Lentils", rank: 100 },
  { name: "Yogurt", rank: 100 },
  { name: "Cheese", rank: 100 },
  { name: "Nuts", rank: 100 },
  // { name: "Milk", rank: 100 },
  // { name: "Ice cream", rank: 100 },
  // { name: "Butter", rank: 100 },
  // { name: "Sour cream", rank: 100 },
  // { name: "Kefir", rank: 100 },
  // { name: "Cottage cheese", rank: 100 },
  // { name: "Whey protein", rank: 100 },
  // { name: "Heavy cream", rank: 100 },
  // { name: "Olive oil", rank: 100 },
  // { name: "Coconut oil", rank: 100 },
  // { name: "Avocado", rank: 100 },
  // { name: "Vegetable oil", rank: 100 },
  // { name: "Canola oil", rank: 100 },
  // { name: "Peanut butter", rank: 100 },
  // { name: "Sunflower seeds", rank: 100 },
  // { name: "Chia seeds", rank: 100 },
  // { name: "Flaxseed", rank: 100 },
  // { name: "Salmon", rank: 100 }, // Added more foods
  // { name: "Tuna", rank: 100 },
  // { name: "Shrimp", rank: 100 },
  // { name: "Chicken breast", rank: 100 },
  // { name: "Ground beef", rank: 100 },
  // { name: "Pork chops", rank: 100 },
  // { name: "Lamb chops", rank: 100 },
  // { name: "Turkey breast", rank: 100 },
  // { name: "Tofu scramble", rank: 100 },
  // { name: "Lentil soup", rank: 100 },
  // { name: "Black bean soup", rank: 100 },
  // { name: "Chicken noodle soup", rank: 100 },
  // { name: "Tomato soup", rank: 100 },
  // { name: "Broccoli soup", rank: 100 },
  // { name: "Apple pie", rank: 100 },
  // { name: "Chocolate cake", rank: 100 },
  // { name: "Cookies", rank: 100 },
  // { name: "Brownies", rank: 100 },
  // { name: "Cupcakes", rank: 100 },
  // { name: "Pizza", rank: 100 },
  // { name: "Hamburger", rank: 100 },
  // { name: "Hot dog", rank: 100 },
  // { name: "Tacos", rank: 100 },
  // { name: "Burrito", rank: 100 },
  // { name: "Sushi", rank: 100 },
  // { name: "Pasta salad", rank: 100 },
  // { name: "Potato salad", rank: 100 },
  // { name: "Coleslaw", rank: 100 },
  // { name: "Mac and cheese", rank: 100 },
  // { name: "Lasagna", rank: 100 },
  // { name: "Spaghetti", rank: 100 },
  // { name: "Eggs Benedict", rank: 100 },
  // { name: "French toast", rank: 100 },
  // { name: "Pancakes", rank: 100 },
  // { name: "Waffles", rank: 100 },
  // { name: "Oatmeal with fruit", rank: 100 },
  // { name: "Yogurt with granola", rank: 100 },
  // { name: "Cereal with milk", rank: 100 },
  // { name: "Trail mix", rank: 100 },
  // { name: "Protein bar", rank: 100 },
  // { name: "Apple juice", rank: 100 },
  // { name: "Orange juice", rank: 100 },
  // { name: "Grape juice", rank: 100 },
];

export default foods;
