app = "runway-rank-proxy"

[build]
  dockerfile = "Dockerfile"

[[services]]
  internal_port = 8000
  protocol = "tcp"

  [[services.ports]]
    handlers = ["http"]
    port = "80"

[[services]]
  internal_port = 8443
  protocol = "tcp"

  [[services.ports]]
    handlers = ["tls", "http"]
    port = "443"

[env]
  PORT = "8000"
  
[[restart]]
  policy = "on-failure"
  retries = 2
  processes = ["app"]