entryPoints:
   web:
      address: ':8000'
   websecure:
      address: ':8443'

providers:
   file:
      filename: /etc/traefik/dynamic_conf.yml

api:
   dashboard: true
   insecure: true

log:
   level: INFO

accessLog: {}
