const foods = [
  { name: "Apple", score: 100, ratings: 0 },
  { name: "Banana", score: 100, ratings: 0 },
  { name: "Orange", score: 100, ratings: 0 },
  { name: "Grape", score: 100, ratings: 0 },
  { name: "Strawberry", score: 100, ratings: 0 },
  { name: "Mango", score: 100, ratings: 0 },
  { name: "Pineapple", score: 100, ratings: 0 },
  { name: "Watermelon", score: 100, ratings: 0 },
  { name: "Blueberry", score: 100, ratings: 0 },
  { name: "Kiwi", score: 100, ratings: 0 },
  { name: "Broccoli", score: 100, ratings: 0 },
  { name: "Carrot", score: 100, ratings: 0 },
  { name: "Potato", score: 100, ratings: 0 },
  { name: "Tomato", score: 100, ratings: 0 },
  { name: "Onion", score: 100, ratings: 0 },
  { name: "Lettuce", score: 100, ratings: 0 },
  { name: "Spinach", score: 100, ratings: 0 },
  { name: "Cucumber", score: 100, ratings: 0 },
  { name: "Bell pepper", score: 100, ratings: 0 },
  { name: "Corn", score: 100, ratings: 0 },
  { name: "Rice", score: 100, ratings: 0 },
  { name: "Bread", score: 100, ratings: 0 },
  { name: "Pasta", score: 100, ratings: 0 },
  { name: "Oatmeal", score: 100, ratings: 0 },
  { name: "Quinoa", score: 100, ratings: 0 },
  { name: "Cornbread", score: 100, ratings: 0 },
  { name: "Couscous", score: 100, ratings: 0 },
  { name: "Barley", score: 100, ratings: 0 },
  { name: "Rye bread", score: 100, ratings: 0 },
  { name: "Wheat berries", score: 100, ratings: 0 },
  { name: "Chicken", score: 100, ratings: 0 },
  { name: "Beef", score: 100, ratings: 0 },
  { name: "Fish", score: 100, ratings: 0 },
  { name: "Eggs", score: 100, ratings: 0 },
  { name: "Tofu", score: 100, ratings: 0 },
  { name: "Beans", score: 100, ratings: 0 },
  { name: "Lentils", score: 100, ratings: 0 },
  { name: "Yogurt", score: 100, ratings: 0 },
  { name: "Cheese", score: 100, ratings: 0 },
  { name: "Nuts", score: 100, ratings: 0 },
  // { name: "Milk", score: 100, ratings: 0 },
  // { name: "Ice cream", score: 100, ratings: 0 },
  // { name: "Butter", score: 100, ratings: 0 },
  // { name: "Sour cream", score: 100, ratings: 0 },
  // { name: "Kefir", score: 100, ratings: 0 },
  // { name: "Cottage cheese", score: 100, ratings: 0 },
  // { name: "Whey protein", score: 100, ratings: 0 },
  // { name: "Heavy cream", score: 100, ratings: 0 },
  // { name: "Olive oil", score: 100, ratings: 0 },
  // { name: "Coconut oil", score: 100, ratings: 0 },
  // { name: "Avocado", score: 100, ratings: 0 },
  // { name: "Vegetable oil", score: 100, ratings: 0 },
  // { name: "Canola oil", score: 100, ratings: 0 },
  // { name: "Peanut butter", score: 100, ratings: 0 },
  // { name: "Sunflower seeds", score: 100, ratings: 0 },
  // { name: "Chia seeds", score: 100, ratings: 0 },
  // { name: "Flaxseed", score: 100, ratings: 0 },
  // { name: "Salmon", score: 100, ratings: 0 }, // Added more foods
  // { name: "Tuna", score: 100, ratings: 0 },
  // { name: "Shrimp", score: 100, ratings: 0 },
  // { name: "Chicken breast", score: 100, ratings: 0 },
  // { name: "Ground beef", score: 100, ratings: 0 },
  // { name: "Pork chops", score: 100, ratings: 0 },
  // { name: "Lamb chops", score: 100, ratings: 0 },
  // { name: "Turkey breast", score: 100, ratings: 0 },
  // { name: "Tofu scramble", score: 100, ratings: 0 },
  // { name: "Lentil soup", score: 100, ratings: 0 },
  // { name: "Black bean soup", score: 100, ratings: 0 },
  // { name: "Chicken noodle soup", score: 100, ratings: 0 },
  // { name: "Tomato soup", score: 100, ratings: 0 },
  // { name: "Broccoli soup", score: 100, ratings: 0 },
  // { name: "Apple pie", score: 100, ratings: 0 },
  // { name: "Chocolate cake", score: 100, ratings: 0 },
  // { name: "Cookies", score: 100, ratings: 0 },
  // { name: "Brownies", score: 100, ratings: 0 },
  // { name: "Cupcakes", score: 100, ratings: 0 },
  // { name: "Pizza", score: 100, ratings: 0 },
  // { name: "Hamburger", score: 100, ratings: 0 },
  // { name: "Hot dog", score: 100, ratings: 0 },
  // { name: "Tacos", score: 100, ratings: 0 },
  // { name: "Burrito", score: 100, ratings: 0 },
  // { name: "Sushi", score: 100, ratings: 0 },
  // { name: "Pasta salad", score: 100, ratings: 0 },
  // { name: "Potato salad", score: 100, ratings: 0 },
  // { name: "Coleslaw", score: 100, ratings: 0 },
  // { name: "Mac and cheese", score: 100, ratings: 0 },
  // { name: "Lasagna", score: 100, ratings: 0 },
  // { name: "Spaghetti", score: 100, ratings: 0 },
  // { name: "Eggs Benedict", score: 100, ratings: 0 },
  // { name: "French toast", score: 100, ratings: 0 },
  // { name: "Pancakes", score: 100, ratings: 0 },
  // { name: "Waffles", score: 100, ratings: 0 },
  // { name: "Oatmeal with fruit", score: 100, ratings: 0 },
  // { name: "Yogurt with granola", score: 100, ratings: 0 },
  // { name: "Cereal with milk", score: 100, ratings: 0 },
  // { name: "Trail mix", score: 100, ratings: 0 },
  // { name: "Protein bar", score: 100, ratings: 0 },
  // { name: "Apple juice", score: 100, ratings: 0 },
  // { name: "Orange juice", score: 100, ratings: 0 },
  // { name: "Grape juice", score: 100, ratings: 0 },
];

export default foods;
